<a href="https://colab.research.google.com/github/atulcoin/face-recognition/blob/master/clb_final_face_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pafy
!pip install imutils pafy youtube-dl

In [2]:
import imutils
import cv2
import pafy
import youtube_dl
from google.colab.patches import cv2_imshow

In [3]:
url = "https://www.youtube.com/watch?v=hoNb6HuNmU0"
vPafy = pafy.new(url)

play = vPafy.getbest(preftype="mp4")

In [4]:
cap = cv2.VideoCapture(play.url)
print(cap.isOpened()) # if in cap we have entered wrong file path then it will give false else true
while(cap.isOpened()):    # TO CAPTURE FRAMES OF CAMERA TO VIEW AS VIDEO 
  #  print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)) # TO PRINT HEIGHT or property OF THE FRAME 
  #  print(cap.get(cv2.CAP_PROP_FRAME_WIDTH)) # TO PRINT WIDTHE OF THE FRAME 
    face_dec = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

    ret, frame= cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) # here i am printing gray image as output
    faces = face_dec.detectMultiScale(gray, scaleFactor =1.05, minNeighbors=5)

    for x,y,w,h in faces:
        gray = cv2.rectangle(gray, (x,y), (x+w,y+h), (0,255,0),2)
        cv2_imshow(gray)
    if cv2.waitKey(1) == 13:  #13 is the asci code of enter key
        break
cap.release()
cv2.destroyAllWindows()

True


error: ignored

training of model with custom data set
**bold text**

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [6]:
from PIL import Image
import os
import numpy as np

bpath = '/content/drive/My Drive/part1face'
image_dir = os.path.join(bpath, "train")

In [46]:
y_label = []
x_train = []

#count = 0

current_id=0
label_id={}


for root, dirs, files in os.walk(image_dir):
  for file in files:
    if file.endswith("png") or file.endswith("jpg"):
      label = os.path.basename(root).replace(" ","-").lower() #we can replace os.path.dirname(path) with root also
      path = os.path.join(root,file)
            #print(label,path)
            
      if not label in label_id:
        label_id[label] = current_id
        current_id +=1
        id_= label_id[label]
        print(id_)
        #img = cv2.imread(path, 1)
        pil_image=  Image.open(path).convert("L") # L to convert image in grey pil image is used to tell sysetem that the file in location is image file
        image_arra=  np.array(pil_image,"uint8")
            #print(image_arra)
            
        y_label.append(id_)
        x_train.append(image_arra)
y_label = np.asarray(y_label, dtype=np.int32)
x_train = np.asarray(x_train, dtype=np.int32)
#model = cv2.face.LBPHFaceRecognizer_create()

#model.train(np.asarray(x_train), np.asarray(y_label))
#with open("labels.pickle", 'wb') as f:
   # pickle.dump(label_id, f)
print("train complete")
print(x_train)
#model.save('save_face.xml')


0
1
2
3
4
5
train complete
[[[128 133 139 ... 105 112 111]
  [127 132 138 ... 105 109 109]
  [128 132 138 ...  99 104 106]
  ...
  [ 55  59  68 ...  38  37  37]
  [ 57  60  70 ...  38  38  38]
  [ 58  61  70 ...  39  38  38]]

 [[ 55  51  47 ...  27  28  29]
  [ 55  51  47 ...  26  28  28]
  [ 55  52  49 ...  27  27  27]
  ...
  [ 32  32  32 ... 250 250 251]
  [ 31  31  31 ... 249 250 251]
  [ 32  31  31 ... 249 249 251]]

 [[ 36  36  36 ...  21  21  21]
  [ 36  36  36 ...  20  20  20]
  [ 36  36  36 ...  19  19  19]
  ...
  [ 32  30  29 ...   7   7   8]
  [ 35  32  30 ...   7   8   8]
  [ 37  35  32 ...   8   8   8]]

 [[ 31  31  31 ... 156 133 114]
  [ 31  31  31 ... 158 133 112]
  [ 32  31  31 ... 161 135 114]
  ...
  [255 255 255 ... 101 112 125]
  [255 255 255 ...  93 102 108]
  [255 255 255 ...  77  83 101]]

 [[142 142 122 ...  22  23  23]
  [141 142 122 ...  22  23  23]
  [139 140 120 ...  22  22  22]
  ...
  [ 13  13  13 ...  12  12  12]
  [ 13  13  13 ...  11  11  11]
  [ 13 

In [ ]:
y_label = y_label.shuffle(10000)

In [47]:
x_train.shape

(6, 200, 200)

In [48]:
len(x_train)

6

In [43]:
x_train = np.array(x_train)

In [44]:
x_train.shape

(6, 200, 200, 3)

In [18]:
x_train = x_train.astype('float32')
y_label =y_label.astype('float32')

In [19]:
x_train /= 255
y_label /=255

In [20]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Dropout, Flatten, MaxPooling2D
import keras

creating validation data set for validating

In [24]:
bpath = '/content/drive/My Drive/part1face'
image_dir = os.path.join(bpath, "validation")

In [25]:
y_vali = []
x_vali = []

#count = 0

current_id=0
label_id={}


for root, dirs, files in os.walk(image_dir):
  for file in files:
    if file.endswith("png") or file.endswith("jpg"):
      label = os.path.basename(root).replace(" ","-").lower() #we can replace os.path.dirname(path) with root also
      path = os.path.join(root,file)
            #print(label,path)
            
      if not label in label_id:
        label_id[label] = current_id
        current_id +=1
        id_= label_id[label]
        print(id_)
        #img = cv2.imread(path, 1)
        pil_image=  Image.open(path).convert("L") # L to convert image in grey pil image is used to tell sysetem that the file in location is image file
        image_arra=  np.array(pil_image,"uint8")
            #print(image_arra)
            
        y_vali.append(id_)
        x_vali.append(image_arra)
y_vali = np.asarray(y_vali, dtype=np.int32)
x_vali = np.asarray(x_vali, dtype=np.int32)
#model = cv2.face.LBPHFaceRecognizer_create()

#model.train(np.asarray(x_train), np.asarray(y_label))
#with open("labels.pickle", 'wb') as f:
   # pickle.dump(label_id, f)
print("validation data complete")
print(x_vali)
#model.save('save_face.xml')


0
1
2
3
4
5
validation data complete
[[[128 133 139 ... 105 112 111]
  [127 132 138 ... 105 109 109]
  [128 132 138 ...  99 104 106]
  ...
  [ 55  59  68 ...  38  37  37]
  [ 57  60  70 ...  38  38  38]
  [ 58  61  70 ...  39  38  38]]

 [[ 55  51  47 ...  27  28  29]
  [ 55  51  47 ...  26  28  28]
  [ 55  52  49 ...  27  27  27]
  ...
  [ 32  32  32 ... 250 250 251]
  [ 31  31  31 ... 249 250 251]
  [ 32  31  31 ... 249 249 251]]

 [[ 36  36  36 ...  21  21  21]
  [ 36  36  36 ...  20  20  20]
  [ 36  36  36 ...  19  19  19]
  ...
  [ 32  30  29 ...   7   7   8]
  [ 35  32  30 ...   7   8   8]
  [ 37  35  32 ...   8   8   8]]

 [[ 31  31  31 ... 156 133 114]
  [ 31  31  31 ... 158 133 112]
  [ 32  31  31 ... 161 135 114]
  ...
  [255 255 255 ... 101 112 125]
  [255 255 255 ...  93 102 108]
  [255 255 255 ...  77  83 101]]

 [[142 142 122 ...  22  23  23]
  [141 142 122 ...  22  23  23]
  [139 140 120 ...  22  22  22]
  ...
  [ 13  13  13 ...  12  12  12]
  [ 13  13  13 ...  11  11  1

In [26]:
x_vali = x_vali.astype('float32')
y_vali =y_vali.astype('float32')

In [27]:
x_vali /= 255
y_vali /=255

In [30]:
import tensorflow as tf


In [40]:
y_label.shape

(6,)

In [41]:
x_train.shape

(6, 200, 200, 3)

In [42]:
x_vali.shape

(6, 200, 200)

In [49]:
input_size = 400
output_size = 6
hidden_layer_size = 100
model = tf.keras.Sequential([
        tf.keras.layers.Flatten(input_shape=(200, 200)),
        tf.keras.layers.Dense(hidden_layer_size, activation='relu'),
        tf.keras.layers.Dense(hidden_layer_size, activation='relu'),
       tf.keras.layers.Dense(output_size, activation='softmax')
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [50]:
model.fit(x_train, y_label, epochs=10, validation_data=(x_vali, y_vali), verbose =2)
print ("training complete")

Epoch 1/10
1/1 - 0s - loss: 71.4192 - accuracy: 0.1667 - val_loss: 18.0668 - val_accuracy: 0.0000e+00
Epoch 2/10
1/1 - 0s - loss: 2213.3047 - accuracy: 0.1667 - val_loss: 25.9176 - val_accuracy: 0.0000e+00
Epoch 3/10
1/1 - 0s - loss: 3744.0957 - accuracy: 0.1667 - val_loss: 14.3019 - val_accuracy: 0.0000e+00
Epoch 4/10
1/1 - 0s - loss: 2917.4622 - accuracy: 0.1667 - val_loss: 0.5151 - val_accuracy: 0.1667
Epoch 5/10
1/1 - 0s - loss: 1590.2587 - accuracy: 0.1667 - val_loss: 5.1903 - val_accuracy: 0.0000e+00
Epoch 6/10
1/1 - 0s - loss: 1851.3525 - accuracy: 0.1667 - val_loss: 5.8952 - val_accuracy: 0.0000e+00
Epoch 7/10
1/1 - 0s - loss: 593.6945 - accuracy: 0.6667 - val_loss: 8.0621 - val_accuracy: 0.1667
Epoch 8/10
1/1 - 0s - loss: 158.3786 - accuracy: 0.6667 - val_loss: 9.7786 - val_accuracy: 0.1667
Epoch 9/10
1/1 - 0s - loss: 71.7399 - accuracy: 0.6667 - val_loss: 10.9391 - val_accuracy: 0.1667
Epoch 10/10
1/1 - 0s - loss: 243.3251 - accuracy: 0.6667 - val_loss: 11.2938 - val_accuracy